// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnW7zranuYTi2vgMKwm_cmf9h435WD3-0',
    appId: '1:143751027251:web:51afad4c0bd357c4bce146',
    messagingSenderId: '143751027251',
    projectId: 'flockwell-d3cb4',
    authDomain: 'flockwell-d3cb4.firebaseapp.com',
    storageBucket: 'flockwell-d3cb4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfoSdiahSsRRQqWkym3XuKGO8jlF8Mgd0',
    appId: '1:143751027251:android:89c6501f0afc1ec4bce146',
    messagingSenderId: '143751027251',
    projectId: 'flockwell-d3cb4',
    storageBucket: 'flockwell-d3cb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyyOv2M1JGxiO6GVSTLTy73VJpUH8QPbY',
    appId: '1:143751027251:ios:5591e50dcc83cd93bce146',
    messagingSenderId: '143751027251',
    projectId: 'flockwell-d3cb4',
    storageBucket: 'flockwell-d3cb4.firebasestorage.app',
    iosBundleId: 'com.flockwell.cockatielCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyyOv2M1JGxiO6GVSTLTy73VJpUH8QPbY',
    appId: '1:143751027251:ios:5591e50dcc83cd93bce146',
    messagingSenderId: '143751027251',
    projectId: 'flockwell-d3cb4',
    storageBucket: 'flockwell-d3cb4.firebasestorage.app',
    iosBundleId: 'com.flockwell.cockatielCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnW7zranuYTi2vgMKwm_cmf9h435WD3-0',
    appId: '1:143751027251:web:d51fa82df7162596bce146',
    messagingSenderId: '143751027251',
    projectId: 'flockwell-d3cb4',
    authDomain: 'flockwell-d3cb4.firebaseapp.com',
    storageBucket: 'flockwell-d3cb4.firebasestorage.app',
  );
}
